### ISSUE TITLE
use encodeURIComponent() for getSuggestions()

### ISSUE THREAD

**Issue by dog42** [KELiON/cerebro-google#1]
In the function getSuggestions() special symbols like `+` should be escaped in `query`. Otherwise, certain requests may be misinterpreted, for example Google's calculator:

![issue](https://user-images.githubusercontent.com/9193069/36066347-294bc606-0ea8-11e8-94aa-d33dc48b6cc6.png)

after adjusting the code, it works:
![issue2](https://user-images.githubusercontent.com/9193069/36066404-2aa94ebe-0ea9-11e8-9887-5d1a7720b04e.png)

use of encodeURIComponent() in getSuggestions():
```
const getSuggestions = (query) => {
  query = encodeURIComponent(query)
  const url = `http://suggestqueries.google.com/complete/search?client=firefox&q=${query}`
  return fetch(url)
    .then(response => response.json())
    .then(response => response[1] || [])
}
```

**Comment by ogustavo-pereira** [comment]
This issue is very old and today we do not maintain this plugin as a preference. because of this I will close
